### PR TITLE
added weather and holiday info

### PR DESCRIPTION
**Pull request by peregrinius**
the weather and holiday info is currently from external APIs.

### CODE REVIEW

**Comment by soobrosa** [comment]
@peregrinius good shot, do you think you can roll regions like Brandenburg and states like California?

**Comment by peregrinius** [comment]
that is on the mental to-do list :)

**Comment by soobrosa** [comment]
do you maybe have an ETA for that?

**Comment by peregrinius** [comment]
End of tomorrow if the Gods are good.

**Comment by soobrosa** [comment]
:+1: get better

**Pull request merged**
